services:
  - type: web
    name: asistente-whatsapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_MAKE_URL
        sync: false